services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: ecuatracker-app
    volumes:
      - .:/var/www/html
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - ecuatracker_net

  nginx:
    image: nginx:stable
    container_name: ecuatracker-nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/custom.conf:/etc/nginx/conf.d/custom.conf
    depends_on:
      - app
    networks:
      - ecuatracker_net

networks:
  ecuatracker_net:
    driver: bridge
